### ISSUE TITLE
Add summary plots to deploy process

### ISSUE THREAD

**Issue by matthewfeickert** [iris-hep/analysis-community-summary#7]
With this time series git-scraping-like deploy setup from PR #6 we will be able to start adding plotting scripts to the CI that run on the time series data to produce summary plots for the current day and for the time series data.

@jpivarski @cranmer @gordonwatts maybe you can think of some summary plots that would be of particular interest. Within a few days we'll hopefully start to have some time series data that isn't just flat in time too. :)

**Comment by matthewfeickert** [comment]
The [Git Scraping](https://simonwillison.net/2020/Oct/9/git-scraping/) and deploy technique is working: c.f. https://github.com/iris-hep/analysis-community-summary/commit/58bfea9f209123177e66f76673c8af039c0453e2

**Comment by gordonwatts** [comment]
There are all sorts of things that don't require that kind of collection - like presentation rate, paper rate, etc.

**Comment by matthewfeickert** [comment]
> There are all sorts of things that don't require that kind of collection - like presentation rate, paper rate, etc.

Is there a list of the things that we're actively tracking as metrics for the NSF? This repo was originally started in response to the scripts that @jpivarski made given a that the

> M.2.5 target is expressed as number of stars (forks, contributors) relative to that number in ROOT

but we're now unable to find where that is currently listed even when checking the Monday board that Rob has. :? If we know the list of metrics we can make plots for them.

**Comment by gordonwatts** [comment]
Ah, that is fantastic. Have you contacted Rob directly? He'd give you something like that! He does have them listed.

**Comment by matthewfeickert** [comment]
I'm going to say that this has been resolved by PR #18 and PR #23, but if @rct225 has thoughts on interesting metrics that we could also be pulling and tracking that aren't being reported at https://iris-hep.org/analysis-community-summary/ yet they are most welcome. It is pretty straightforward to start Git scraping and recording additional metrics, as PR #23 shows. :+1:
